# Generated by Django 4.2.28 on 2026-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('father_name', models.CharField(max_length=255, verbose_name="Father's Name")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('college_code', models.CharField(max_length=50, verbose_name='College Code')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('year_of_study', models.CharField(max_length=20, verbose_name='Year of Study')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='CGPA')),
                ('reason_for_course', models.JSONField(default=list, verbose_name='Reasons for Course')),
                ('area_of_interest', models.JSONField(default=list, verbose_name='Areas of Interest')),
                ('skills_to_develop', models.JSONField(default=list, verbose_name='Skills to Develop')),
                ('plan_after_graduation', models.CharField(choices=[('job', 'Job'), ('higher_studies', 'Higher Studies'), ('entrepreneurship', 'Entrepreneurship'), ('civil_services', 'Civil Services'), ('other', 'Other')], max_length=50, verbose_name='Plan After Graduation')),
                ('interested_in_abroad', models.BooleanField(default=False, verbose_name='Interested in Studying Abroad')),
                ('preferred_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Country')),
                ('career_goal_type', models.CharField(choices=[('technical', 'Technical Expert'), ('management', 'Management'), ('research', 'Research'), ('teaching', 'Teaching'), ('other', 'Other')], max_length=50, verbose_name='Career Goal Type')),
                ('internship_completed', models.BooleanField(default=False, verbose_name='Internship Completed')),
                ('interested_in_internship', models.BooleanField(default=True, verbose_name='Interested in Internship')),
                ('has_certifications', models.BooleanField(default=False, verbose_name='Has Certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
