# Generated by Django 4.2.28 on 2026-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='career_goal_type',
            field=models.CharField(choices=[('Technical Career', 'Technical Career'), ('Management Career', 'Management Career'), ('Research Career', 'Research Career'), ('Government Sector', 'Government Sector'), ('Business / Startup', 'Business / Startup'), ('Undecided', 'Undecided')], max_length=100, verbose_name='Career Goal Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plan_after_graduation',
            field=models.CharField(choices=[('Higher Studies in India', 'Higher Studies in India'), ('Higher Studies Abroad', 'Higher Studies Abroad'), ('Job in India', 'Job in India'), ('Job Abroad', 'Job Abroad'), ('Start a Business', 'Start a Business'), ('Competitive Exams', 'Competitive Exams'), ('Not Decided', 'Not Decided')], max_length=100, verbose_name='Plan After Graduation'),
        ),
    ]
